export const testData = [
    {
      "firstName": "Alice",
      "lastName": "Johnson",
      "avatarUrl": "/avatars/alice.jpg",
      "companyName": "Tech Innovators",
      "designation": "Frontend React",
      "email": "alice.johnson@example.com",
      "contactNo": "9876543210",
      "experience": "4 years",
      "joiningDate": "2022-05-10",
      "team": "Marketing",
      "manager": "Robert Brown"
    },
    {
      "firstName": "Bob",
      "lastName": "Smith",
      "avatarUrl": "/avatars/bob.jpg",
      "companyName": "Tech Innovators",
      "designation": "Backend Developer",
      "email": "bob.smith@example.com",
      "contactNo": "8765432109",
      "experience": "5 years",
      "joiningDate": "2021-03-15",
      "team": "Engineering",
      "manager": "Sophie Davis"
    },
    {
      "firstName": "Charlie",
      "lastName": "Brown",
      "avatarUrl": "/avatars/charlie.jpg",
      "companyName": "Tech Innovators",
      "designation": "UI/UX Designer",
      "email": "charlie.brown@example.com",
      "contactNo": "7654321098",
      "experience": "3 years",
      "joiningDate": "2022-07-22",
      "team": "Design",
      "manager": "Sophie Davis"
    },
    {
      "firstName": "Diana",
      "lastName": "Miller",
      "avatarUrl": "/avatars/diana.jpg",
      "companyName": "Tech Innovators",
      "designation": "Data Analyst",
      "email": "diana.miller@example.com",
      "contactNo": "6543210987",
      "experience": "6 years",
      "joiningDate": "2020-11-30",
      "team": "Analytics",
      "manager": "Robert Brown"
    },
    {
      "firstName": "Ethan",
      "lastName": "Johnson",
      "avatarUrl": "/avatars/ethan.jpg",
      "companyName": "Tech Innovators",
      "designation": "DevOps Engineer",
      "email": "ethan.johnson@example.com",
      "contactNo": "5432109876",
      "experience": "4 years",
      "joiningDate": "2021-06-18",
      "team": "Operations",
      "manager": "Alice Johnson"
    },
    {
      "firstName": "Fiona",
      "lastName": "Williams",
      "avatarUrl": "/avatars/fiona.jpg",
      "companyName": "Tech Innovators",
      "designation": "Project Manager",
      "email": "fiona.williams@example.com",
      "contactNo": "4321098765",
      "experience": "7 years",
      "joiningDate": "2019-09-01",
      "team": "Management",
      "manager": "Robert Brown"
    },
    {
      "firstName": "George",
      "lastName": "Taylor",
      "avatarUrl": "/avatars/george.jpg",
      "companyName": "Tech Innovators",
      "designation": "QA Engineer",
      "email": "george.taylor@example.com",
      "contactNo": "3210987654",
      "experience": "2 years",
      "joiningDate": "2023-01-10",
      "team": "Quality Assurance",
      "manager": "Sophie Davis"
    },
    {
      "firstName": "Hannah",
      "lastName": "Davis",
      "avatarUrl": "/avatars/hannah.jpg",
      "companyName": "Tech Innovators",
      "designation": "Content Strategist",
      "email": "hannah.davis@example.com",
      "contactNo": "2109876543",
      "experience": "5 years",
      "joiningDate": "2020-04-25",
      "team": "Content",
      "manager": "Alice Johnson"
    },
    {
      "firstName": "Ian",
      "lastName": "Wilson",
      "avatarUrl": "/avatars/ian.jpg",
      "companyName": "Tech Innovators",
      "designation": "System Administrator",
      "email": "ian.wilson@example.com",
      "contactNo": "1098765432",
      "experience": "8 years",
      "joiningDate": "2016-12-15",
      "team": "IT",
      "manager": "Robert Brown"
    },
    {
      "firstName": "Jasmine",
      "lastName": "Lee",
      "avatarUrl": "/avatars/jasmine.jpg",
      "companyName": "Tech Innovators",
      "designation": "Marketing Specialist",
      "email": "jasmine.lee@example.com",
      "contactNo": "0987654321",
      "experience": "3 years",
      "joiningDate": "2021-08-22",
      "team": "Marketing",
      "manager": "Sophie Davis"
    },
    {
      "firstName": "Kyle",
      "lastName": "Anderson",
      "avatarUrl": "/avatars/kyle.jpg",
      "companyName": "Tech Innovators",
      "designation": "Business Analyst",
      "email": "kyle.anderson@example.com",
      "contactNo": "9876501234",
      "experience": "4 years",
      "joiningDate": "2022-03-05",
      "team": "Business",
      "manager": "Alice Johnson"
    }
  ]
  
  